### ISSUE TITLE
Crash reported by a user of my modpack.

### ISSUE THREAD

**Issue by Slayer5934** [Jomcraft-Network/DefaultSettings#15]
[crash-2023-04-25_13.14.25-client.txt](https://github.com/Jomcraft-Network/DefaultSettings/files/11322233/crash-2023-04-25_13.14.25-client.txt)

This user reported a crash when the game finished loading, not sure what in the world would cause it to though.

**Comment by PT400C** [comment]
Hey @Slayer5934,

it seems that you're using a version of the mod from early 2021. Just a few weeks ago I've published an update to major revision 4 on Forge 1.12.2. 

Would it be possible for you to upgrade?

**Comment by Slayer5934** [comment]
Indeed, I can do that (: I will close the issue then re-open if it happens again, sorry for the trouble.

**Comment by PT400C** [comment]
No problem, just be sure to create backup before upgrading 👍🏻
