### ISSUE TITLE
Options file doesn't apply Forge 1.20.1

### ISSUE THREAD

**Issue by Proxwian** [Jomcraft-Network/DefaultSettings#23]
After saving all configs via /defaultsettings saveAll command and removing options.txt file, after restart mod only applies keybind settings, but lang and guy scale, as well as other options doesn't applies from mod DefaultSettings folder

**Comment by PT400C** [comment]
This is intended behavior. If you ran those commands and delete the `options.txt` file afterwards, the mod will treat this as a local change of settings (as the `ds_private_storage.json` file knows that the `options.txt` file has already been created before). It won't interfere with it and thus those files will contain standard values.

If you want to ship the modpack, you must exclude the `options.txt` file **AND** the `ds_private_storage.json` file. To simulate that, you could locally delete both of these files. Then with the next startup the mod will set the correct settings.

**Comment by Proxwian** [comment]
OK, I would try and write to you afterwards

**Comment by Proxwian** [comment]
My bad, that's true: deleting ```ds_private_storage.json``` helps. Closing.

**Comment by PT400C** [comment]
You're welcome :) Feel free to reopen in case you notice another issue with that particular feature.
