### ISSUE TITLE
Error message in log for 1.18.1 Forge

### ISSUE THREAD

**Issue by nanonestor** [Jomcraft-Network/DefaultSettings#9]
Error with parameter 'destfile' - 

Forge 39.1.2
DefaultSettings-1.18.x-2.8.0

[Snip of just the error](https://paste.gg/p/anonymous/f57fe785ada743f8a35cb8b7c6bd2ed3)
[latest.log](https://paste.gg/p/anonymous/b93b240e2d9b4b1eaf5614217b4f236c)

**Comment by PT400C** [comment]
@nanonestor Hey, would you be willing to share your pack folder (e.g. as a ZIP) with me? Also, what exactly did you do to cause this error?

PT400C#8363

**Comment by nanonestor** [comment]
Yeah - it's simply giving that on game load.  It's been set up by doing the /ds saveconfigs command

**Comment by PT400C** [comment]
This issue should be fixed with DefaultSettings 2.8.1 (3.5.1 for Fabric).
